### ISSUE TITLE
Maali created duplicate folders due to symlink (?)

### ISSUE THREAD

**Issue by Halolegend94** [PawseySC/maali-cygnet#361]
Looking at the list of folders representing OSes in ``/group/pawsey0001/software``  folder I get

```
-bash-4.2$ ls
centos7.6  cle60up05  cle60up07  sles12sp3  topaz_centos7.6
```

``topaz_centos7.6`` and ``centos7.6`` should be the same one right?

Cheers

**Comment by marcodelapierre** [comment]
Thanks @Halolegend94 .

For now you're right, we should only have centos7.6 for Topaz, because this is the current naming convention for this cluster. topaz_centos7.6 was a leftover of a test I did, it was an empty dir, so I deleted it.

Going forward, if we decide to switch an existing cluster to the new naming convention, we might get the two directory trees in peaceful coexistence.
